language: php

php:
    - 7.1

install:
    - composer self-update
    - composer install

script:
    - ./vendor/bin/phpunit --config tests/phpunit/phpunit.xml;
    - ./vendor/bin/phpspec run --config tests/phpspec/phpspec.yml --no-interaction;
    - ./vendor/bin/behat --config tests/behat/behat.yml --suite inline;
